Walker.create(name:"Ralph", schedule: "Weekends", price: 100)
Walker.create(name:"Ralph", schedule: "Weekends", price: 100)
Walker.create(name:"Ralph",schedule:  "Weekends", price: 100)
Walker.create(name: "Ralph",schedule:  "Weekends", price: 100)

Dog.create(name: "John", breed: "Wolf", walked: true)
Dog.create(name: "Yearld", breed: "Wolf",walked: true)
Dog.create(name: "Eric", breed: "Bird",walked: false)
Dog.create(name: "Julio", breed: "Tiger",walked: false)
Dog.create(name: "Earl", breed: "Lion", walked:false)
DogWalker.create(dog_id: 1, walker_id: 7)
DogWalker.create(dog_id: 3, walker_id: 2)
DogWalker.create(dog_id: 1, walker_id: 1)
DogWalker.create(dog_id: 4, walker_id: 3)
DogWalker.create(dog_id: 2, walker_id: 5)
DogWalker.create(dog_id: 1, walker_id: 4)
Walker.create(name: "Julio",schedule:  "Weekends", price: 150)
Walker.create(name: "Ryan",schedule:  "Weekends", price: 90)
Walker.create(name: "Moe",schedule:  "Weekday", price: 42)
Walker.create(name: "Stacy",schedule:  "Weekdays", price: 12)
Walker.create(name: "Vic",schedule:  "Weekends", price: 2)
Walker.create(name: "Adam",schedule:  "Weekends", price: 32)
Walker.create(name: "Kaylin",schedule:  "Weekdays", price: 22)
Walker.create(name: "Ian",schedule:  "Weekdays", price: 52)
Walker.create(name: "Drew",schedule:  "Weekdays", price: 39)

Dog.create(name: "Eric", breed: "Bird",walked: false)
Dog.create(name: "Andy", breed: "Fish",walked: false)
Dog.create(name: "Jil", breed: "Salmon",walked: false)
DogWalker.create(dog_id: 4, walker_id: 2)
DogWalker.create(dog_id: 2, walker_id: 5)
DogWalker.create(dog_id: 1, walker_id: 6)
DogWalker.create(dog_id: 5, walker_id: 2)
Dog.create(name: "Carlos", breed: "Eagle",walked: false)
Dog.create(name: "Erica", breed: "Pig",walked: false)
